name: cote
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^2.25.4

  # Firebase Auth
  firebase_auth: ^4.17.4

  # Cloud Firestore
  cloud_firestore: ^4.15.4

  # Firebase Storage
  firebase_storage: ^11.6.6
  google_generative_ai: ^0.2.0 

  # For picking videos (teachers upload shorts)
  image_picker: ^1.0.7

  # For previewing videos (students see shorts)
  video_player: ^2.7.0
  file_selector: ^0.9.3
  flutter_pdfview: ^1.0.0
  path_provider: ^2.1.1
  cached_network_image: ^3.3.1


  # HTTP package to ensure compatibility with googleapis_auth
  http: ^1.0.0

  # Google APIs
  googleapis: ^14.0.0   # Upgrade to this version
  googleapis_auth: ^1.5.0  # Compatible version for googleapis

  # PDF handling
  pdf: ^3.6.0
  pdfx: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints for Flutter projects
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Uncomment this section to add assets for your app.
  assets:
    - assets/service-account.json  # Add the service account file here

  # Fonts (if any)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
